const liveUrl = 'https://marziehnail-atelier.dk/da/';

export const metadata = {
  title: 'Marzieh Nail Atelier Brand & Digital Launch Case | Romaric Clementi',
  description: 'Markedsresearch, identitetsretning, tilbudsarkitektur, tosproget website-produktion, lokale søgefundamenter, QA og overdragelse for Marzieh Nail Atelier i Valby.',
  alternates: { canonical: '/da/arbejde/marzieh-nail-atelier/', languages: { en: '/work/marzieh-nail-atelier/', da: '/da/arbejde/marzieh-nail-atelier/' } },
  openGraph: { title: 'Marzieh Nail Atelier Brand & Digital Launch Case | Romaric Clementi', description: 'Fra lokale markedssignaler og identitetsretninger til et live tosproget brand-til-booking-system.', type: 'article', images: [{ url: '/assets/marzieh-desktop-proof-4p9-37-v687.webp', alt: 'Marzieh Nail Atelier website-interface' }] },
};

const marketSignals = [
  ['Servicefokuseret salonkommunikation', 'Gør den private 1:1 atelieroplevelse til en del af værdien, ikke kun behandlingslisten.'],
  ['Travle eller volumenprægede signaler', 'Brug et roligere redaktionelt system bygget omkring tid, præcision og personlig opmærksomhed.'],
  ['Generiske menuer med lidt vejledning', 'Skab serviceveje, praktisk guidance og et signaturkoncept før booking.'],
  ['Booking før tillid', 'Placér dokumentation, priser, politikker, besøgsinformation og forventninger i beslutningsvejen.'],
];
const identityDirections = [
  { code: 'A', title: 'Skulpturel editorial', text: 'Kunstnerisk, taktil og udtryksfuld. Stærk stemning, men for dominerende til det daglige servicesystem.', mark: 'M' },
  { code: 'B', title: 'Botanisk monogram', text: 'En raffineret M-baseret retning med en fin organisk accent og stærkere genkendelse i små formater.', mark: 'M' },
  { code: 'C', title: 'Roligt ateliersystem', text: 'Valgt retning. Monogram, redaktionelt ordmærke, afdæmpede varme neutraler og en roligere premium-rytme.', mark: 'M', selected: true },
];
const launchSystem = [
  ['01', 'Marked', 'Lokale konkurrent-signaler og kundernes forventninger'], ['02', 'Positionering', 'Privat 1:1, rolig omsorg, personlig kunst og tydelig vejledning'], ['03', 'Identitet', 'Logoretninger, valgt monogram, typografi og visuel tone'], ['04', 'Tilbud', 'Services, priser, signaturkoncepter, politikker og bookinglogik'], ['05', 'Indhold', 'EN/DA-kildestruktur, tillid, vejledning og lokal information'], ['06', 'Oplevelse', 'Responsive ruter fra opdagelse til servicevalg og booking'], ['07', 'Synlighed', 'Metadata, strukturerede data, Business Profile og indekseringsarbejde'], ['08', 'Release', 'QA, deployment, måling, versionering og ejeroverdragelse'],
];
const searchProof = [
  ['Lokale søgefundamenter', 'Sidemetadata, strukturerede data, sprogruter, sitemap-/indekseringstjek og lokal virksomhedsinfo.'],
  ['Google-økosystem', 'Business Profile-alignment, services og visuelt proof, Search Console-arbejde og review-/tillidssynlighed.'],
  ['Bookingmåling', 'Google-relateret konverteringsinstrumentering og Planway-bookinglink-tjek blev bygget ind i auditerede produktionspakker.'],
  ['Tillid før konvertering', 'Reviews, adresse, politikker, servicevejledning og bookingforventninger blev behandlet som en del af anskaffelsesrejsen.'],
];
const evidence = [
  ['Let levering', 'Holdt implementeringen praktisk at deploye, gennemgå og overdrage med lokale assets og tydelig kildekontrol.'],
  ['Sprogparitet', 'Kontrollerede engelsk og dansk service-, pris-, politik- og bookinglogik samlet for at reducere indholdsdrift.'],
  ['Release-QA', 'Verificerede navigation, responsiv adfærd, bookinghandlinger, links, metadata, lokale assets og indholdsparitet før release.'],
  ['Ejeroverdragelse', 'Versionsstyret kildepakke, deploy-noter, beslutninger om forretningskilder og tydelige næste skridt.'],
];
const routeArchitecture = [
  ['Kundesti', ['Forside', 'Services', 'Galleri', 'Bridal', 'Besøg', 'Book']],
  ['Tillid og vejledning', ['Atelier', 'Standarder', 'Reviews', 'Guides', 'FAQ']],
  ['Praktisk', ['Politikker', 'Privatliv']],
];
const releaseControl = [
  ['Mobil', ['Smalle layouts', 'Navigation og booking-CTA', 'Billedbeskæring og læsbarhed']],
  ['Sprog', ['EN / DA-ruteparitet', 'Service-, pris- og politikparitet', 'Bookinglogik']],
  ['Release', ['Links og ankre', 'Metadata og strukturerede data', 'Lokale assets og build-status']],
  ['Overdragelse', ['Versionsstyret source', 'Deployment-noter', 'Forretningskilde-beslutninger']],
];


export default function MarziehCaseStudyDa() {
  const caseSchema = { '@context': 'https://schema.org', '@type': 'CreativeWork', name: 'Marzieh Nail Atelier brand- og digital launch-case', creator: { '@type': 'Person', name: 'Romaric Clementi' }, url: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://romaric-digital-portfolio.clementiromaric.workers.dev'}/da/arbejde/marzieh-nail-atelier/`, mainEntityOfPage: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://romaric-digital-portfolio.clementiromaric.workers.dev'}/da/arbejde/marzieh-nail-atelier/`, about: { '@type': 'WebSite', name: 'Marzieh Nail Atelier', url: liveUrl }, inLanguage: ['da', 'en'], description: 'Markeds-, identitets-, indholds-, website-, lokal-søge- og produktionsarbejde for et live tosproget selvstændigt negleatelier.' };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(caseSchema) }} />
    <header className="bar case-bar"><div className="wrap bar__in"><a className="brand" href="/da/#work" aria-label="Tilbage til Romaric Clementis portfolio"><b>RC</b><span>Romaric Clementi</span></a><nav className="case-nav" aria-label="Case-navigation"><a href="/da/#work">← Tilbage til portfolio</a><span className="lang-switch" role="group" aria-label="Sprogvalg"><a href="/work/marzieh-nail-atelier/">EN</a><span aria-hidden="true">/</span><a aria-current="page" href="/da/arbejde/marzieh-nail-atelier/">DA</a></span><a className="btn case-live-cta" href={liveUrl} target="_blank" rel="noopener noreferrer"><span className="case-live-cta__desktop">Besøg website ↗</span><span className="case-live-cta__mobile">Website ↗</span></a></nav></div></header>
    <main className="case-page case-page--editorial">
      <section className="case-hero case-hero--editorial"><div className="wrap"><nav className="case-breadcrumb" aria-label="Brødkrummer"><a href="/da/">Portfolio</a><span>/</span><strong>Marzieh Nail Atelier</strong></nav><div className="case-title-block"><p className="mono">Case 01 · live virksomhed</p><h1>Marzieh Nail Atelier</h1><p className="case-subtitle">Brand-, markeds- og digitalt launch-system for et selvstændigt negleatelier i Valby.</p><p className="case-hero__lede">Jeg var med til at forme atelierets position ud fra lokale markeds- og konkurrentsignaler, udviklede identitetsretninger med ejeren og omsatte derefter den valgte retning til tilbud, tosproget website, lokal søgning, bookingrejse, QA og overdragelse.</p><div className="case-hero__actions"><a className="btn" href="#project">Se projektdetaljer</a><a className="text-link" href={liveUrl} target="_blank" rel="noopener noreferrer">Besøg live website ↗</a></div></div>
      <div className="project-glance" aria-label="Projektet kort fortalt"><div><span>Kontekst</span><p>Et reelt implementeret projekt for min kones selvstændige virksomhed; ikke en betalt ekstern kundeopgave.</p></div><div><span>Mit ansvar</span><p>Markeds- og konkurrentgennemgang, positionering, identitetsretninger, tilbuds-/indholdsarkitektur, website-produktion, lokale søgefundamenter, responsiv QA, deployment og overdragelse.</p></div><div><span>Resultat</span><p>Et live EN/DA brand-til-booking-system med afstemte services, priser, politikker, lokal tillid, søgefundamenter og ejerstyrede kilder.</p></div></div>
      <div className="case-proof-strip" aria-label="Aktuel og dateret virksomhedsproof"><div><b>EN / DA</b><span>Live tosproget system</span></div><div><b>4.9 / 37</b><span>Google-rating / reviews · live 12. aug. 2026</span></div><div><b>163</b><span>Business Profile-interaktioner · jul. 2026</span></div><div><b>1:1</b><span>Privat atelier-position</span></div></div><p className="case-proof-note">Synlighedstal er signaler på virksomhedsniveau i liveperioden. De præsenteres ikke som website-only attribution.</p>
      <figure className="case-cover case-cover--liveproof"><img className="case-transition-image" src="/assets/marzieh-desktop-proof-4p9-37-v687.webp" width="1600" height="873" fetchPriority="high" decoding="async" alt="Reelt desktop-skærmbillede af Marzieh Nail Atelier-websitet" /><figcaption>Reelt desktop-skærmbillede · danske og engelske ruter</figcaption></figure></div></section>
      <section id="project" className="case-section"><div className="wrap case-section__grid"><div className="case-section__heading"><p className="mono">01 / Research og mulighed</p><h2>Websitet begyndte før websitet.</h2></div><div className="case-copy"><p>Det tidlige arbejde var ikke kun sidedesign. Jeg gennemgik lokale negle- og beautykonkurrenter sammen med ejeren og så på, hvordan tilbud, pris, visuel tone, tillid og booking blev præsenteret. Formålet var praktisk: at finde ud af, hvor et privat én-til-én atelier kunne være meningsfuldt anderledes uden at kopiere kategorien.</p><p>Det var en mindre lokal konkurrentgennemgang, ikke et formelt markedsresearch-program. Den gav nok signal til at vælge en roligere, mere personlig og vejledningsdrevet retning.</p></div></div><div className="wrap market-signal-grid" aria-label="Sanitiserede markedssignaler og muligheder">{marketSignals.map(([pattern, opportunity]) => <article key={pattern}><span>Observeret mønster</span><h3>{pattern}</h3><p>{opportunity}</p></article>)}</div></section>
      <section className="case-section case-section--identity"><div className="wrap"><div className="case-section__heading case-section__heading--wide"><p className="mono">02 / Positionering og identitet</p><h2>Omsæt markedsretningen til et genkendeligt ateliersystem.</h2></div><div className="case-section__grid case-section__grid--identity"><div className="case-copy"><p>Positioneringen blev et privat én-til-én atelier bygget omkring rolig tid, præcis forberedelse, personlig kunst og tydelig vejledning før produktvalg. Jeg udviklede flere logo- og identitetsretninger, gennemgik dem med Marzieh, forfinede den valgte rute og førte den ind i den digitale oplevelse og udvalgte fysiske touchpoints.</p><p>Marzieh forblev virksomhedsejer og endelig beslutningstager. Min rolle var at researche, rammesætte muligheder, bygge retninger, gøre trade-offs tydelige og omsætte den valgte retning til et konsistent system.</p></div><div className="identity-final-card"><p className="mono">Valgt system</p><div className="identity-final-card__mark" aria-hidden="true">M</div><h3>Roligt atelier</h3><p>Redaktionelt ordmærke, afdæmpede varme neutraler, et raffineret monogram og nok luft til, at neglearbejdet og grundlæggerens stemme forbliver fokus.</p><div className="identity-palette" aria-label="Sanitiseret paletteretning"><i /><i /><i /><i /></div></div></div><div className="identity-directions" aria-label="Sanitiseret identitetskort">{identityDirections.map((item) => <article key={item.code} className={item.selected ? 'is-selected' : ''}><span className="identity-directions__code">{item.code}</span><div className="identity-directions__mark" aria-hidden="true">{item.mark}</div><div><h3>{item.title}{item.selected ? <small>Valgt</small> : null}</h3><p>{item.text}</p></div></article>)}</div><p className="artefact-note">Sanitiseret retningskort. Det opsummerer identitetsarbejdet frem for at reproducere hvert oprindeligt logoudkast.</p></div></section>
      <section className="case-section case-section--launch"><div className="wrap"><div className="case-section__heading case-section__heading--wide"><p className="mono">03 / Launch-system</p><h2>Forbind brandbeslutninger med det system, mennesker faktisk bruger.</h2></div><p className="launch-system__intro">Projektets stærkeste del er forbindelsen mellem research, forretningsbeslutninger og implementering. Hvert lag skulle hænge sammen med det næste.</p><div className="launch-system" aria-label="Launch-system fra marked til release">{launchSystem.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="case-section case-section--screens"><div className="wrap"><div className="case-section__heading case-section__heading--wide"><p className="mono">04 / Live oplevelse</p><h2>Brandet bliver nyttigt, når kunder kan træffe en sikker beslutning.</h2></div><div className="case-gallery-editorial case-gallery-editorial--real case-gallery-editorial--balanced"><figure className="case-shot case-shot--signature"><div className="case-shot__media"><img src="/assets/marzieh-composition-full-v687.webp" width="688" height="1487" loading="lazy" decoding="async" alt="Reelt mobilskærmbillede af The Atelier Composition-siden" /></div><figcaption><span>Signaturservice</span>Positioneringen bliver en konkret design-led service med tydelig forklaring og bookingvej.</figcaption></figure><figure className="case-shot case-shot--service"><div className="case-shot__media"><img src="/assets/marzieh-service-path-proof-v687.webp" width="688" height="1020" loading="lazy" decoding="async" alt="Reelt mobilskærmbillede af Marzieh Nail Ateliers servicesektion: Choose the right service path first" /></div><figcaption><span>Servicearkitektur</span>Brandkontekst giver plads til praktisk valg, tid, pris og det korrekte næste skridt.</figcaption></figure><figure className="case-shot case-shot--guide"><div className="case-shot__media"><img src="/assets/marzieh-guide-proof-v687.webp" width="688" height="1430" loading="lazy" decoding="async" alt="Reelt mobilskærmbillede af Gel Nails vs Shellac-guiden" /></div><figcaption><span>Guideindhold</span>Nyttig information reducerer gætteri før booking og understøtter et mere gennemtænkt servicevalg.</figcaption></figure></div></div></section>
      <section className="case-section case-section--visibility"><div className="wrap"><div className="case-section__heading case-section__heading--wide"><p className="mono">05 / Søgning, Google og lokal synlighed</p><h2>En lokal virksomhedslancering er ikke færdig, når siderne renderer.</h2></div><div className="case-section__grid"><div className="case-copy"><p>Jeg behandlede opdagelse, tillid og booking som sammenhængende dele af kunderejsen. Arbejdet gik ud over on-page copy til lokale søgefundamenter, Google-vendt virksomhedsinfo, indekseringstjek og bookingmåling.</p><p>Jeg påstår ikke, at website-arbejdet alene skabte virksomhedstallene. Tallene her er transparente driftssignaler fra liveperioden og bruges som kontekst for systemet omkring websitet.</p></div><div className="visibility-metrics" aria-label="Søge- og lokal virksomhedsproof"><article><b>163</b><span>Google Business Profile-interaktioner</span><small>Juli 2026</small></article><article><b>4.9</b><span>Google-rating</span><small>37 reviews på live site · 12. aug. 2026</small></article><article><b>EN / DA</b><span>Sprogarkitektur</span><small>Søge- og kunderejser holdt på linje</small></article></div></div><div className="case-evidence-board case-evidence-board--visibility">{searchProof.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="case-section case-section--production"><div className="wrap"><div className="case-section__heading case-section__heading--wide"><p className="mono">06 / Tekniske beslutninger og overdragelse</p><h2>Hold løsningen praktisk efter lancering.</h2></div><p className="production-artefacts__intro">To sanitiserede produktionsartefakter gør implementeringsarbejdet synligt i stedet for kun at beskrive det. Rutekortet afspejler den nuværende live navigation; release-boardet opsummerer de kontroller, der holder mobil, sprog, release og overdragelse på linje.</p><div className="production-artefacts"><article className="production-artefact production-artefact--routes"><div className="production-artefact__head"><span className="mono">Artefakt 01</span><h3>Live indholds- og rutearkitektur</h3><p>Offentligt indhold grupperet omkring beslutning, tillid og praktiske behov, hvor engelsk og dansk behandles som ét system.</p></div><div className="route-architecture" aria-label="Sanitiseret live rute- og indholdsarkitektur">{routeArchitecture.map(([group, items]) => <div className="route-architecture__group" key={group}><b>{group}</b><div>{items.map((item, index) => <span key={item}>{item}{index < items.length - 1 ? <i aria-hidden="true">→</i> : null}</span>)}</div></div>)}<div className="route-architecture__parity"><span>EN</span><i aria-hidden="true">↔</i><span>DA</span><small>Samme beslutningslogik på offentlige ruter</small></div></div></article><article className="production-artefact production-artefact--release"><div className="production-artefact__head"><span className="mono">Artefakt 02</span><h3>QA-, release- og overdragelseskontrol</h3><p>Et kompakt overblik over de kontroller, der gør en færdig side til en release, som kan stoles på og vedligeholdes.</p></div><div className="release-control" aria-label="Sanitiseret QA-, release- og overdragelsescheckliste">{releaseControl.map(([group, items]) => <div key={group}><b>{group}</b><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></article></div><p className="artefact-note">Sanitiserede driftsartefakter baseret på live-projektet og release-workflowet. De viser ikke private loginoplysninger, interne kontodata eller implementeringshemmeligheder.</p><div className="case-evidence-board">{evidence.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="production-disclosure"><h3>AI-assisteret produktion</h3><p>Claude, ChatGPT og andre AI-værktøjer understøttede research, udkast, kodehjælp og sammenligning. Jeg definerede brief og retning, udvalgte og reviderede output, testede implementeringen, traf de endelige beslutninger og havde ansvaret for deployment og overdragelse.</p></div></div></section>
      <section className="case-outcome case-outcome--editorial"><div className="wrap case-outcome__grid"><div><p className="mono">Det viser projektet</p><h2>Research, brandimplementering og digital produktion kan hænge sammen hele vejen til overdragelse.</h2></div><div><p>Projektet viser et bredere leveringsmønster end et website-build alene: læs markedet, gør positioneringsvalg synlige, udvikl identitetsmuligheder, strukturér tilbud og kildemateriale, byg kunderejsen, understøt lokal synlighed, test releasen og efterlad ejeren med et system, der kan fortsætte.</p><div className="case-outcome__actions"><a className="btn" href={liveUrl} target="_blank" rel="noopener noreferrer">Besøg live website ↗</a><a className="btn btn--ghost" href="/da/#contact">Kontakt mig</a></div></div></div></section>
    </main>
    <footer><div className="wrap foot"><div className="mark"><b>RC</b><span>Uklart menneskeligt og forretningsmæssigt behov → klart digitalt system.</span></div><div className="fine">Marzieh Nail Atelier case · Romaric Clementi</div></div></footer>
  </>;
}
